---
  title: "worksheet#2-mov_rev1"
author: "Darlene Erl Lapso"
output: pdf_document
date: "2024-02-06"
---

```{r}
library(xml2)
library(rvest)
library(httr)
library(polite)
```

```{r}
polite::use_manners(save_as = 'polite_scrape.R')
```

```{r}
#for pagination URL
url_template <- 'https://www.imdb.com/title/tt0817177/reviews/_ajax?ref_=undefined&paginationKey=%s'
```

```{r}
scrape_page <- function(url_template, pagination_key) {
  session <- bow(sprintf(url_template, pagination_key), user_agent = "Educational")
  
  #Scrape Data
  #USERNAME
  Usernames <- scrape(session) %>% 
    html_nodes('span.display-name-link') %>% 
    html_text()
  
  #DATE
  Date <- scrape(session) %>% 
    html_nodes('span.review-date') %>% 
    html_text()
  
  #CONTENT
  Content <- scrape(session) %>% 
    html_nodes('div.text.show-more__control') %>% 
    html_text()
  
  #RATING
  Rating <- scrape(session) %>% 
    html_nodes('span.rating-other-user-rating') %>% 
    html_text()
  
  #extract for the next page
  pagination_key <- scrape(session) %>% html_nodes("div.load-more-data") %>% html_attr("data-key")
  
  return(list(Usernames = Usernames, Date = Date, Content = Content, Rating = Rating, pagination_key = pagination_key))
}
```

```{r}
movie_name <- "FLIPPED"
movie_name_vector <- rep(movie_name, length(Usernames))
Usernames <- character(0)
Date <- character(0)
Content <- character(0)
Rating <- character(0)
pagination_key <- ""
```

```{r}
#scrape multiple pages
reviews_to_scrape <- 300
per_page <- 25
pages_to_scrape <- ceiling(reviews_to_scrape / per_page)
```

```{r}
#for loop

for (page in 1:pages_to_scrape) {
  scraped_data <- scrape_page(url_template, pagination_key)
  
  Usernames <- c(Usernames, scraped_data$Usernames)
  Date <- c(Date, scraped_data$Date)
  Content <- c(Content, scraped_data$Content)
  Rating <- c(Rating, scraped_data$Rating)
  
  pagination_key <- scraped_data$pagination_key
  
  #condition for specified length of reviews
  if (length(Usernames) >= reviews_to_scrape) {
    break
  }
}
```

```{r}
# Create a data frame
FLIPPED <- data.frame(
  Movie_name = movie_name_vector[1:length(Usernames)],
  Usernames = Usernames[1:length(Usernames)],
  Date = Date[1:length(Usernames)],
  Content = Content[1:length(Usernames)],
  Rating = Rating[1:length(Usernames)]
)
```

```{r}
# Save as CSV
write.csv(FLIPPED, file = "FLIPPED.csv", row.names = FALSE)
```

```{r}
# Print the data frame
print(FLIPPED)
```












