---
title: "GRAVEOFFIREFLIES_movrev.rmd"
author: "Darlene Erl Lapso"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(xml2)
library(rvest)
library(httr)
library(polite)
```

```{r}
#######################################   2ND MOVIE

polite::use_manners(save_as = 'polite_scrape.R')
```



```{r}
#for pagination URL
toyStory <- 'https://www.imdb.com/title/tt0095327/reviews/_ajax?ref_=undefined&paginationKey=%s' 
```

```{r}
toyPage <- function(toyStory, toyPK) {
  url <- sprintf(toyStory, toyPK)
  
  # Use tryCatch to handle errors
  tryCatch({
    # Use bow() with the constructed URL
    toySession <- bow(url, user_agent = "Educational")
    
    # Scrape Data
    #USERNAME
    TSUsernames <- scrape(toySession) %>% 
      html_nodes('span.display-name-link') %>% 
      html_text()
    
    #DATE
    TSDate <- scrape(toySession) %>% 
      html_nodes('span.review-date') %>% 
      html_text()
    
    #CONTENT
    TSContent <- scrape(toySession) %>% 
      html_nodes('div.text.show-more__control') %>% 
      html_text()
    
    #RATING
    TSRating <- scrape(toySession) %>% 
      html_nodes('span.rating-other-user-rating') %>% 
      html_text()
    
    #extract for the next page
    nexttoyPK <- scrape(toySession) %>% html_nodes("div.load-more-data") %>% html_attr("data-key")
    
    return(list(Usernames = TSUsernames, Date = TSDate, Content = TSContent, Rating = TSRating, nexttoyPK = nexttoyPK))
  }, error = function(e) {
    # Print error message
    message("Error in toyPage(): ", conditionMessage(e))
    # Return empty list
    return(list(Usernames = character(0), Date = character(0), Content = character(0), Rating = character(0), nexttoyPK = ""))
  })
}

```

```{r}
movie_name <- "GRAVE OF THE FIREFLIES"
movie_name_vector <- rep(movie_name, length(Usernames))
TSUsernames <- character(0)
TSDate <- character(0)
TSContent <- character(0)
TSRating <- character(0)
toyPK <- ""
```

```{r}
#scrape multiple pages
toyTotal_Rev <- 300
toyPerPage <- 25
toyToScrape <- ceiling(toyTotal_Rev / toyPerPage)
```

```{r}
#for loop
for (page in 1:toyToScrape) {
  toy_scraped_data <- toyPage(toyStory, toyPK)
  
  TSUsernames <- c(TSUsernames, toy_scraped_data$Usernames)
  TSDate <- c(TSDate, toy_scraped_data$Date)
  TSContent <- c(TSContent, toy_scraped_data$Content)
  TSRating <- c(TSRating, toy_scraped_data$Rating)
  
  toyPK <- toy_scraped_data$nexttoyPK
  
  #condition for specified length of reviews
  if (length(TSUsernames) >= toyTotal_Rev) {
    break
  }
}
```

```{r}
# Create a data frame
GRAVE_OF_FIREFLIES <- data.frame(
  Movie_name = movie_name_vector[1:length(Usernames)],
  Usernames = TSUsernames[1:length(Usernames)],
  Date = TSDate[1:length(Usernames)],
  Content = TSContent[1:length(Usernames)],
  Rating = TSRating[1:length(Usernames)]
)
```

```{r}
# Save as CSV
write.csv(GRAVE_OF_FIREFLIES, file = "GRAVE_OF_FIREFLIES.csv", row.names = FALSE)
```

```{r}
# Print the data frame
print(GRAVE_OF_FIREFLIES)
View(GRAVE_OF_FIREFLIES)
```